version: '3'
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    container_name: mysql-ts
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  api:
    container_name: api-ts
    build:
      dockerfile: dev.dockerfile
      context: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'

volumes:
  db: